### PR TITLE
errors in x_texts.amb fixed

### PR DESCRIPTION
**Pull request by skdubg**
- still found many spelling mistakes while playing
- adjustments for female heroes
- more errors fixed from the previous release (in version 1.08)

### CODE REVIEW

**Review by Pyrdacor — COMMENTED** [review]
I will check this tomorrow on my PC and then approve/merge. ;)

**Comment by skdubg** [comment]
review requested - i doesn't wonted klick this - do not feel pressured :D
what does the checks by appveyor mean? green and red? it is important?

**Comment by Pyrdacor** [comment]
I see you are still very active. Let me know when you think you're done and I will review it all together. ;)

**Comment by skdubg** [comment]
> I see you are still very active. Let me know when you think you're done and I will review it all together. ;)

oh that I'm probably only when I have played through the game 2 to 3 more times :D
It's amazing how many spelling mistakes are hiding in it. I think if you are planning to release v1.1 would be a good time to check and merge the files

**Comment by Pyrdacor** [comment]
I merged your changes into the master branch. However I fixed/reverted some changes but most are integrated. There were also 2 '\' characters which I removed. The word "RICHTGE" looks wrong but is ok in poetry like the riddlemouth.

**Comment by Pyrdacor** [comment]
Good job btw. ;)

**Comment by skdubg** [comment]
Thank you. I will now wait until the 1.1 with the new game files is out.

**Pull request closed without merging**
